name: Maintenance Mode

on:
 push:
  branches:
   - master

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2

   - name: Get Version
     shell: bash
     id: get-version
     run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

   - name: Zip Files
     working-directory: ./
     run: zip -r ./module.zip ./*

   - name: Create Release
     id: create-release
     uses: ncipollo/release-action@v1
     with:
      allowUpdates: true
      name: Version ${{ steps.get-version.outputs.version }}
      draft: false
      preselease: false
      token: ${{secrets.GITHUB_TOKEN}}
      artifacts: './module.zip, ./module.json'
      tag: Stable